export const FILTER_KEYWORD = "FILTER_KEYWORD";
export const FILTER_SETJOBS = "FILTER_SETJOBS";
export const FILTER_SETSELECTEDJOB = "FILTER_SETSELECTEDJOB";
export const FILTER_LOADINGJOBS = "FILTER_LOADINGJOBS";
export const FILTER_LOADINGJOBSID = "FILTER_LOADINGJOBSID";
